import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import {
  FolderKanban, CheckSquare, Users, BarChart3, Search, Mail,
  LockKeyhole, Eye, EyeOff, ShieldCheck, Zap, Smartphone, Headphones,
  ArrowRight, TrendingUp, CheckCircle2, Package, Plus, Pencil, Trash2
} from 'lucide-react';
import api from '../services/api';
import { getUser, isAdmin } from '../lib/auth';
import PageHead from '../components/PageHead';
import StatCard from '../components/StatCard';
import AuthShell from '../components/AuthShell';

function Dashboard(){const [projects,setProjects]=useState([]);const [tasks,setTasks]=useState([]);useEffect(()=>{Promise.all([api.get('/projects'),api.get('/tasks')]).then(([p,t])=>{setProjects(p.data||[]);setTasks(t.data||[])}).catch(()=>{})},[]);const completed=tasks.filter(t=>t.status==='Completed').length;const progress=tasks.filter(t=>t.status==='In Progress').length;const avg=projects.length?Math.round(projects.reduce((a,p)=>a+(p.progress||0),0)/projects.length):0;return <><PageHead title="Dashboard" sub={`Good morning, ${getUser()?.name||'User'}! Here's what's happening with your projects today.`}/><div className="stats-grid"><StatCard icon={FolderKanban} title="Total Projects" value={projects.length} change="Live database data" kind="teal"/><StatCard icon={CheckSquare} title="Total Tasks" value={tasks.length} change={`${completed} completed`} kind="red"/><StatCard icon={TrendingUp} title="In Progress" value={progress} change="Live database data" kind="green"/><StatCard icon={CheckCircle2} title="Completed" value={completed} change="Live database data" kind="blue"/></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h2>Project Progress</h2><small>Overall project completion</small></div></div><div className="progress-layout"><div className="donut" style={{'--progress':`${avg*3.6}deg`}}><div>{avg}%<small>Complete</small></div></div><div className="legend"><span><i className="dot completed"/>Completed <b>{completed}</b></span><span><i className="dot progress"/>In Progress <b>{progress}</b></span><span><i className="dot pending"/>Pending <b>{Math.max(tasks.length-completed-progress,0)}</b></span></div></div></section><section className="panel"><div className="panel-head"><div><h2>Recent Activity</h2><small>Latest tasks from database</small></div></div><div className="activity-list">{tasks.slice(0,5).map(t=><div className="activity" key={t._id}><div className="avatar small">{(t.assignee?.name||'U').slice(0,2).toUpperCase()}</div><div><b>{t.title}</b><small>{t.project?.name||'No project'}</small></div><time>{t.status}</time></div>)}{!tasks.length&&<div className="empty-state">No tasks found in database.</div>}</div></section></div><section className="panel project-overview"><div className="panel-head"><div><h2>Projects Overview</h2><small>Live projects from database</small></div><Link className="text-btn" to="/projects">View all</Link></div><div className="mini-projects">{projects.slice(0,3).map(p=><div className="mini-project" key={p._id}><div className="project-thumb teal"><FolderKanban size={19}/></div><div><b>{p.name}</b><small>{p.category}</small><div className="bar"><i style={{width:`${p.progress||0}%`}}/></div><small>{p.progress||0}% complete</small></div></div>)}{!projects.length&&<div className="empty-state">No projects found in database.</div>}</div></section></>}

export default Dashboard;
