import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import {
  FolderKanban, CheckSquare, Users, BarChart3, Search, Mail,
  LockKeyhole, Eye, EyeOff, ShieldCheck, Zap, Smartphone, Headphones,
  ArrowRight, TrendingUp, CheckCircle2, Package, Plus, Pencil, Trash2
} from 'lucide-react';
import api from '../services/api';
import { getUser, isAdmin } from '../lib/auth';
import PageHead from '../components/PageHead';
import StatCard from '../components/StatCard';
import AuthShell from '../components/AuthShell';

function Tasks(){const [items,setItems]=useState([]);const [projects,setProjects]=useState([]);const [form,setForm]=useState({title:'',project:'',priority:'Medium',dueDate:''});const [show,setShow]=useState(false);const [query,setQuery]=useState('');const load=()=>api.get('/tasks').then(r=>setItems(r.data||[])).catch(e=>alert(e.response?.data?.message||'Unable to load tasks'));useEffect(()=>{load();api.get('/projects').then(r=>setProjects(r.data||[])).catch(()=>{})},[]);const add=async e=>{e.preventDefault();try{await api.post('/tasks',form);setShow(false);setForm({title:'',project:'',priority:'Medium',dueDate:''});load()}catch(err){alert(err.response?.data?.message||'Only admin can create tasks')}};const update=async(t,status)=>{try{await api.put('/tasks/'+t._id,{status});load()}catch(err){alert(err.response?.data?.message||'You can update only assigned tasks')}};const filtered=items.filter(t=>t.title.toLowerCase().includes(query.toLowerCase()));return <><PageHead title="Tasks" sub="Update and track real tasks from the database." action={isAdmin()&&<button className="primary-btn" onClick={()=>setShow(!show)}><Plus size={16}/> New Task</button>}/>{show&&<form className="panel form-panel" onSubmit={add}><h2>Create Task</h2><div className="form-grid"><input required placeholder="Task title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select required value={form.project} onChange={e=>setForm({...form,project:e.target.value})}><option value="">Select project</option>{projects.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Low</option><option>Medium</option><option>High</option></select><input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></div><button className="primary-btn">Save Task</button></form>}<div className="panel"><div className="task-toolbar"><div className="search-box"><Search size={16}/><input placeholder="Search tasks..." value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{filtered.length} task(s)</span></div><div className="task-table"><div className="task-row task-head"><span>Title</span><span>Project</span><span>Priority</span><span>Due Date</span><span>Status</span><span>Action</span></div>{filtered.map(t=><div className="task-row" key={t._id}><b>{t.title}</b><span>{t.project?.name||'—'}</span><span className={'priority '+t.priority.toLowerCase()}>{t.priority}</span><span>{t.dueDate?new Date(t.dueDate).toLocaleDateString():'—'}</span><select value={t.status} onChange={e=>update(t,e.target.value)} disabled={!isAdmin()&&String(t.assignee?._id)!==String(getUser()?.id)}><option>To Do</option><option>In Progress</option><option>Completed</option></select><MoreVertical size={16}/></div>)}{!filtered.length&&<div className="empty-state">No tasks found in database.</div>}</div></div></>}

export default Tasks;
